close #9 - add ability to cancel unflip
veteran29/vet_unflipping pull request #18
Opened 2019-07-10 20:03 UTC by McDiod

* needs CBA >= 3.12.0
* makes unflip progressbar closeable
* sends stop event to server if unflip progressbar is closed
* checks continuously for _requiredUnits both on server and client

2019-07-10 20:59 UTC, veteran29 requested changes
Thank you very much for this! Looks robust. 

I've only some code-style related suggestions.

2019-07-10 20:59 UTC, veteran29 commented on addons/unflipping/XEH_preInitClient.sqf
> +                params ["_args","","_elapsedTime"];
```suggestion
                params ["_args", "", "_elapsedTime"];
```

2019-07-10 20:59 UTC, veteran29 commented on addons/unflipping/XEH_preInitClient.sqf
> +                params ["_args","","","","_failureCode"];
```suggestion
                params ["_args", "", "", "", "_failureCode"];
```

2019-07-10 20:59 UTC, veteran29 commented on addons/unflipping/XEH_preInitClient.sqf
> +                    if (PLAYER in (_vehicle getVariable ["vet_unflippingUnits",[]])) then {
```suggestion
                    if (PLAYER in (_vehicle getVariable ["vet_unflippingUnits", []])) then {
```

2019-07-10 20:59 UTC, veteran29 commented on addons/unflipping/XEH_preInitServer.sqf
> +                params ["_vehicle","_requiredUnits"];
```suggestion
                params ["_vehicle", "_requiredUnits"];
```

2019-07-10 20:59 UTC, veteran29 commented on addons/unflipping/XEH_preInitServer.sqf
> +            [_vehicle,_requiredUnits],
```suggestion
            [_vehicle, _requiredUnits],
```

2019-07-10 20:59 UTC, veteran29 commented on addons/unflipping/functions/fn_unflipAction.sqf
> +            params ["_args","","","","_failureCode"];
```suggestion
            params ["_args", "", "", "", "_failureCode"];
```

2019-07-11 14:13 UTC, McDiod commented
Oh yea, I tried to match your style, but apparently forgot about the array spaces along the way.

2019-07-11 14:24 UTC, merged