Fr localisation
veteran29/vet_unflipping pull request #24
Opened 2020-01-09 19:19 UTC by NorXAengell

French translation ;)

2020-01-09 23:01 UTC, veteran29 requested changes

2020-01-09 23:01 UTC, veteran29 commented on addons/unflipping/stringtable.xml
> +        <French>Limite de masse individuelle </French>
```suggestion
        <French>Limite de masse individuelle</French>
```

2020-01-09 23:01 UTC, veteran29 commented on addons/unflipping/stringtable.xml
> +        <French>Définit le poid pouvant être retourné par une seule unité. La valeur par défaut devrait permettre à une seule unité de retourner la plupart des petits véhicules.  </French>
```suggestion
        <French>Définit le poid pouvant être retourné par une seule unité. La valeur par défaut devrait permettre à une seule unité de retourner la plupart des petits véhicules.</French>
```

2020-01-09 23:01 UTC, veteran29 commented on addons/unflipping/stringtable.xml
> +        <French>Limite d'hommes </French>
```suggestion
        <French>Limite d'hommes</French>
```

2020-01-09 23:01 UTC, veteran29 commented on addons/unflipping/stringtable.xml
> +        <French>Temps de retournement </French>
```suggestion
        <French>Temps de retournement</French>
```

2020-01-09 23:01 UTC, veteran29 commented on addons/unflipping/stringtable.xml
> +        <French>Poids maximum de retournement </French>
```suggestion
        <French>Poids maximum de retournement</French>
```

2020-01-09 23:01 UTC, veteran29 commented on addons/unflipping/stringtable.xml
> +        <French>Nombre de personnes pour retourner : %1</French>
Is this space before ` :` wanted?
```suggestion
        <French>Nombre de personnes pour retourner: %1</French>
```

2020-01-09 23:02 UTC, veteran29 commented
Thank you very much for submitting this translation!

I've found some minor issues, you can apply my suggestions in batch in "Files changed" tab

2020-01-10 01:29 UTC, NorXAengell commented
Thx for your comments. In french from France there is a space before and after ponctuation like !?:
So between a word and ":" there's always a space before and after.

However the correction is ok for the second. It's ok for you ?

2020-01-10 15:37 UTC, veteran29 commented
There's still some whitespace in settings names which seems unnecesary.

2020-01-11 16:25 UTC, NorXAengell commented
Could you please say where ? ^^.
If for exemple here: <French>Limite de masse individuelle </French>
It's normal in french to have whitespace between word and ":" before and after it. 
The other way is a spelling error.

2020-01-11 16:30 UTC, veteran29 commented
I've just recognized that there is `:` after setting name in CBA. My bad.

2020-01-11 16:30 UTC, veteran29 approved these changes
Thanks again!

2020-01-11 16:30 UTC, merged

2020-01-11 16:30 UTC, NorXAengell commented
No probleme thx to you :)